package com.ncl.common


object Constants {

    // Request Codes
    val REQUEST_CODE_AUTH_COORDINATOR_FIREBASE_AUTH = 1001


    // Coordinator Ids
    val APP_COORDINATOR_ID = "APP_COORDINATOR"
    val ONBOARDING_COORDINATOR_ID = "ONBOARDING_COORDINATOR"
    val SPLASH_COORDINATOR_ID = "SPLASH_COORDINATOR"
    val AUTH_COORDINATOR_ID = "AUTH_COORDINATOR"


    // Fragment Ids
    val SPLASH_FRAGMENT_TAG = "SPLASH_FRAGMENT"
    val AUTH_FRAGMENT_TAG = "AUTH_FRAGMENT"
    val LOGIN_FRAGMENT_TAG = "LOGIN_FRAGMENT"
    val SIGNUP_FRAGMENT_TAG = "SIGNUP_FRAGMENT"

}
