package com.ncl.common


object Constants {

    // Request Codes
    val REQUEST_CODE_LOGIN_COORDINATOR_FIREBASE_AUTH = 1001


    // Coordinator Ids
    val APP_COORDINATOR_ID = "APP_COORDINATOR"
    val ONBOARDING_COORDINATOR_ID = "ONBOARDING_COORDINATOR"
    val SPLASH_COORDINATOR_ID = "SPLASH_COORDINATOR"
    val LOGIN_COORDINATOR_ID = "LOGIN_COORDINATOR"


    // Fragment Ids
    val SPLASH_FRAGMENT_TAG = "SPLASH_FRAGMENT"
    val LOGIN_FRAGMENT_TAG = "LOGIN_FRAGMENT"


    // Dependency Providers Ids
    val DEFAULT_ACTIVITY_PROVIDER_ID = "DEFAULT_ACTIVITY_PROVIDER"
    val DEFAULT_SCREEN_SERVICE_ID = "DEFAULT_SCREEN_SERVICE"
    val DEFAULT_USER_MANAGER_SERVICE_ID = "DEFAULT_USER_MANAGER_SERVICE"

}