package com.intervalintl.workflow.common


object Constants {

    // Request Codes
    val REQUEST_CODE_LOGIN_COORDINATOR_FIREBASE_AUTH = 1001


    // Coordinator Ids
    val ONBOARD_FLOW_ID = "ONBOARD_FLOW"
    val LOGIN_FLOW_ID = "LOGIN_FLOW"


    // Fragment Ids
    val SPLASH_FRAGMENT_TAG = "SPLASH_FRAGMENT"
    val LOGIN_FRAGMENT_TAG = "LOGIN_FRAGMENT"


    // Dependency Providers Ids
    val DEFAULT_ACTIVITY_PROVIDER_ID = "DEFAULT_ACTIVITY_PROVIDER"
    val DEFAULT_FLOW_VIEWPORT_SERVICE_ID = "DEFAULT_FLOW_VIEWPORT_SERVICE"
    val DEFAULT_USER_MANAGER_SERVICE_ID = "DEFAULT_USER_MANAGER_SERVICE"

}